Added user management crud and profile update option
InfyOmLabs/adminlte-generator pull request #64
Opened 2020-02-24 13:23 UTC by ankitInfyOm

2020-02-29 06:14 UTC, vishalinfyom requested changes

2020-02-29 06:14 UTC, vishalinfyom commented on app/Http/Controllers/UserController.php
> +
remove extra space

2020-02-29 06:14 UTC, vishalinfyom commented on app/Http/Controllers/UserController.php
> +        return view('users.show')->with('User', $user);
`U`  should be small  in User

2020-02-29 06:14 UTC, vishalinfyom commented on app/Http/Controllers/UserController.php
> +
remove extra space

2020-02-29 06:14 UTC, vishalinfyom commented on app/Http/Controllers/UserController.php
> +     * @param  UpdateUserProfileRequest  $request
add one line when tag is changed

2020-02-29 06:14 UTC, vishalinfyom commented on app/Http/Controllers/UserController.php
> +
remove this line

2020-02-29 06:14 UTC, vishalinfyom commented on app/Http/Requests/UpdateUserProfileRequest.php
> +        $rules['name'] =  'required|unique:users,name,'.$id;
unique validations should not applied to name, so remove it

2020-02-29 06:14 UTC, vishalinfyom commented on app/Http/Requests/UpdateUserRequest.php
> +        $rules['name'] =  'required|unique:users,name,'.$id;
remove unique name validations

2020-02-29 06:14 UTC, vishalinfyom commented on app/Models/User.php
> +        'is_email_verified',
replace this field by `email_verified_at`

2020-02-29 06:14 UTC, vishalinfyom commented on app/Models/User.php
> +    public function getImagePathAttribute($value)
remove this if not used anywhere, because we already have `img_avatar` mutator

2020-02-29 06:14 UTC, vishalinfyom commented on app/Repositories/BaseRepository.php
> +    public function findWithoutFail($id, $columns = ['*'])
add documentations of this function

2020-02-29 06:14 UTC, vishalinfyom commented on app/Repositories/UserRepository.php
> +     * @throws ApiOperationFailedException
put one line when tag is changed

2020-02-29 06:14 UTC, vishalinfyom commented on app/Repositories/UserRepository.php
> +
remove extra line

2020-02-29 06:14 UTC, vishalinfyom commented on app/Repositories/UserRepository.php
> +     * @param $input
add reference type and put one line below

2020-02-29 06:14 UTC, vishalinfyom commented on app/Repositories/UserRepository.php
> +            if (! empty($input['password'])) {
remove whole this if else of password

2020-02-29 06:14 UTC, vishalinfyom commented on app/Repositories/UserRepository.php
> +            if (isset($post['password']) && ! empty($post['password'])) {
take this code at below of try catch

2020-02-29 06:14 UTC, vishalinfyom commented on app/Repositories/UserRepository.php
> +                $user->save();
remove this its not needed, when code is moved to up

2020-02-29 06:14 UTC, vishalinfyom commented on composer.json
> +      "files": ["app/helpers.php"],
format it proper

2020-02-29 06:14 UTC, vishalinfyom commented on routes/web.php
> +    Route::post('profile', 'UserController@updateProfile');
this route name should be `update-profile`

2020-02-29 06:14 UTC, vishalinfyom commented on resources/views/users/show.blade.php
> +
add title here

2020-02-29 06:14 UTC, vishalinfyom commented on resources/views/users/index.blade.php
> +      $(document).ready(function () {
where you are using this code ??

2020-02-29 06:14 UTC, vishalinfyom commented on resources/views/users/index.blade.php
> +        $('#users_table').DataTable({
id should be in camelCase e.g `tblUsers`

2020-02-29 06:14 UTC, vishalinfyom commented on resources/views/users/index.blade.php
> +    <script>
move this scripts to separate users file it should be placed at `public/assets/users/user.js`

2020-02-29 06:14 UTC, vishalinfyom commented on resources/views/users/edit.blade.php
> +    <script>
move this script to separate file

2020-02-29 06:14 UTC, vishalinfyom commented on resources/views/users/create.blade.php
> +    <script>
move this scripts to separate file

2020-02-29 06:14 UTC, vishalinfyom commented on resources/views/profile/edit.blade.php
> +        window.displayPhoto = function (input, selector) {
make this code to common as this is using everywhere, so move it to custom.js and use it from there

2020-02-29 06:14 UTC, vishalinfyom commented on resources/views/profile/edit.blade.php
> +        $(document).on('change', '#editUserImage', function () {
move this code to separate js and better to make this code common

2020-02-29 06:14 UTC, vishalinfyom commented on resources/views/layouts/app.blade.php
> +@yield('page_js')
page js is duplicated

2020-02-29 06:14 UTC, vishalinfyom commented on resources/model_schemas/User.json
> +        "validations": null,
remove this file, its not needed

2020-02-29 06:14 UTC, vishalinfyom commented on public/js/custom.js
> +window.displayPhoto = function (input, selector) {
use this function from everywhere instead of adding same function

2020-02-29 06:14 UTC, vishalinfyom commented on public/js/custom.js
> +        $('#EditProfileModal').modal('show');
id should be in camel case e.g `editProfileModal`

2020-02-29 06:14 UTC, vishalinfyom commented on public/js/custom.js
> +        $('#edit_preview_photo').attr('src',user.image_avatar);
id should be in camel case everywhere

2020-02-29 06:14 UTC, vishalinfyom commented on public/js/custom.js
> +// require('@coreui/coreui');
remove commented code

2020-02-29 06:14 UTC, vishalinfyom commented on public/js/custom.js
> +if ($.fn.dataTable !== undefined) {
remove this datatables code, because we are using yajra datatalbes from backend

2020-02-29 06:14 UTC, vishalinfyom commented on public/css/style.css
> +#movies_table.table-bordered tbody td {
remove all un-used styles

2020-02-29 11:25 UTC, ajayinfyom requested changes
@ankitInfyOm  need to changes also in this PR

- Remove composer.lock
- Use CDN instant of added local all JS and CSS files
- Remove Extra added CDN links (unused) from app.blade.php
- remove twice include custom.js in from app.blade.php
- Why moved User model inside `Models` - revert it
- removed dummy uploaded images

2020-03-02 12:45 UTC, vishalinfyom requested changes

2020-03-02 12:45 UTC, vishalinfyom commented on database/factories/UserFactory.php
> +        'email' => $faker->word,
format code

2020-03-02 12:45 UTC, vishalinfyom commented on public/js/custom.js
> +window.deleteItemInputConfirmation = function (
this is not used anywhere so remove it

2020-03-02 12:45 UTC, vishalinfyom commented on public/js/custom.js
> +window.manageAjaxErrors = function (data, errorDivId = 'editValidationErrorsBox') {
this is not used wnywhere

2020-03-02 12:45 UTC, vishalinfyom commented on public/js/custom.js
> +window.displaySuccessMessage = function (message) {
not used anywhere

2020-03-02 12:45 UTC, vishalinfyom commented on resources/views/layouts/app.blade.php
> +    <link rel="stylesheet" href="https://rawgit.com/fronteed/iCheck/1.x/skins/all.css">
remove all un-used cdn's

2020-03-02 12:45 UTC, vishalinfyom commented on resources/views/layouts/datatables_js.blade.php
> +<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
why datatable version is downgraded ??

2020-03-02 12:45 UTC, vishalinfyom commented on resources/views/layouts/menu.blade.php
> +    <a href="{{ route('users.index') }}"><i class="fa fa-edit"></i><span>Users</span></a>
change icon to `fa fa-users`

2020-03-02 12:45 UTC, vishalinfyom commented on resources/views/profile/edit.blade.php
> +
remove extra line

2020-03-02 12:45 UTC, vishalinfyom commented on resources/views/profile/edit.blade.php
> +            displayPhoto(this, '#edit_preview_photos')
add semicolon everywhere, when line ends.

2020-03-02 12:45 UTC, vishalinfyom commented on resources/views/profile/show.blade.php
> +@extends('layouts.app')
add title

2020-03-02 12:45 UTC, vishalinfyom commented on resources/views/users/create.blade.php
> +
add title

2020-03-02 12:45 UTC, vishalinfyom commented on routes/web.php
> +    Route::get('update-profile', 'UserController@editProfile');
GET route should be just `profile` and update route should be `update-profile`, need to change get route to just `profile` or `profile-details`

2020-03-07 07:34 UTC, ajayinfyom requested changes

2020-03-07 07:34 UTC, ajayinfyom commented on config/datatables-buttons.php
> +         * Output: App\DataTables\UserDataTable
not needed, revert it.

2020-03-07 07:34 UTC, ajayinfyom commented on app/Exceptions/ApiOperationFailedException.php
> + * Company: InfyOm Technologies, Copyright 2019, All Rights Reserved.
remove this doc

2020-03-07 07:34 UTC, ajayinfyom commented on resources/views/users/fields.blade.php
> +    {!! Form::text('name', null, ['id'=>'name','class' => 'form-control','required']) !!}
need to add one space after `,`  you need to check everywhere.

like: `['id'=>'name', 'class' => 'form-control', 'required']`

2020-03-07 07:34 UTC, ajayinfyom commented on resources/views/users/show_fields.blade.php
> +    {!! Form::label('password', 'Password:') !!}
Don't show password field here.

2020-03-07 07:42 UTC, ajayinfyom requested changes
* I think need to show User image in sidebar instant of InfyOm logo

2020-03-30 08:58 UTC, artoon approved these changes

2020-03-31 09:19 UTC, ajayinfyom approved these changes

2020-03-31 09:21 UTC, merged