Implemented laravel spatie permission package and role crud
InfyOmLabs/adminlte-generator pull request #65
Opened 2020-02-29 05:04 UTC by ankitInfyOm

2020-02-29 07:05 UTC, vishalinfyom requested changes

2020-02-29 07:05 UTC, vishalinfyom commented on app/Http/Controllers/RoleController.php
> +            throw new BadRequestHttpException(
this exception should be `UnprocessableEntrity`

2020-02-29 07:05 UTC, vishalinfyom commented on app/Repositories/UserRepository.php
> +            $user =User::create($input);
add space after `=`

2020-02-29 07:05 UTC, vishalinfyom commented on database/seeds/PermissionTableSeeder.php
> +                'description'  => 'User tab visible',
Can Manage Users

2020-02-29 07:05 UTC, vishalinfyom commented on resources/views/roles/create.blade.php
> +
add title everywhere

2020-02-29 07:05 UTC, vishalinfyom commented on resources/views/users/index.blade.php
> +        deleteItem('{{url('users')}}/' + id, '#users_table', 'User');
id should be `tblUsers`

2020-02-29 07:05 UTC, vishalinfyom commented on resources/views/roles/edit_fields.blade.php
> +                @if(in_array($key,$roles->permissions->pluck('id')->toArray()))
need to refactor this

2020-03-07 08:16 UTC, ajayinfyom reviewed
- Remove `composer.lock` file.
- Need to merge the latest code.

2020-03-07 08:16 UTC, ajayinfyom commented on app/Http/Requests/UpdateRoleRequest.php
> +        $rules['name'] = 'required|unique:roles,name,'.$this->route('role')->id;
here, need to override existing rules from the role model.
```
$rules = Role::$rules;
$rules['name'] = 'required|unique:roles,name,'.$this->route('role')->id; 
```

2020-05-30 11:54 UTC, ajayinfyom requested changes
* Also need to be fixed against to Laravel 7.0

2020-05-30 11:54 UTC, ajayinfyom commented on app/Http/Controllers/RoleController.php
> +        return view('roles.edit')->with(['roles' => $role, 'permissions' => $permissions]);
its should be `role`.

2020-05-30 11:54 UTC, ajayinfyom commented on app/Http/Controllers/UserController.php
> +        $selectedRoles = $user->roles()->pluck('role_id')->toArray();
change `$selectedRoles` to `$selectedRole`

2020-05-30 11:54 UTC, ajayinfyom commented on resources/views/users/edit_fields.blade.php
> +    {!! Form::select('role_ids[]',$roles, $selectedRoles, ['class' => 'form-control','id'=>'editRoleId','multiple'=>true,'required']) !!}
change  `$selectedRoles` to `$selectedRole`

2020-05-30 11:54 UTC, ajayinfyom commented on app/Http/Controllers/RoleController.php
> +        $this->rolesRepository = $rolesRepo;
change to `$rolesRepo` to `$roleRepository`

2022-01-24 12:04 UTC, ShaileshInfyom commented
no longer valid

2022-01-24 12:04 UTC, closed without merging